package com.google.android.gms.common.api.internal;

import com.google.android.gms.common.api.C2789g;
import com.google.android.gms.common.api.C2789g.C2788a;
import com.google.android.gms.common.api.C2814k;
import com.google.android.gms.common.api.C2815l;
import com.google.android.gms.common.api.Status;
import java.util.concurrent.TimeUnit;

public final class bq<R extends C2814k> extends C2789g<R> {
    /* renamed from: a */
    private final Status f11472a;

    /* renamed from: d */
    final Status m14178d() {
        return this.f11472a;
    }

    /* renamed from: a */
    public final R mo2376a(long j, TimeUnit timeUnit) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    /* renamed from: a */
    public final void mo2377a() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    /* renamed from: b */
    public final boolean mo2381b() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    /* renamed from: a */
    public final void mo2379a(C2815l<? super R> c2815l) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    /* renamed from: a */
    public final void mo2380a(C2815l<? super R> c2815l, long j, TimeUnit timeUnit) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    /* renamed from: a */
    public final void mo2378a(C2788a c2788a) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    /* renamed from: c */
    public final Integer mo2382c() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }
}
